---
app:
  name: "gonflict"

game:
  enemy_spawners:
    - [0, 0]   # Левый верхний угол
    - [6, 0]   # Центр сверху
    - [12, 0]  # Правый верхний угол
  players_spawners:
    - [4, 12]
    - [8, 12]
